### ISSUE TITLE
package import failure

### ISSUE THREAD

**Issue by RB-HGG** [MoiseRousseau/PyGeoStudio#11]
High there,

I've successfully installed PyGeoStudio via pip, but run into an error when I try to load it in a Jupyter Notebook.

I get the following error below. Any help would be greatly appreciated!

Traceback (most recent call last):

  File [c:\Users\XXXXX\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3369](file:///C:/Users/XXXXX/anaconda3/lib/site-packages/IPython/core/interactiveshell.py:3369) in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Input [In [6]](vscode-notebook-cell:?execution_count=6%3E) in <cell line: 1>
    import PyGeoStudio as pgs

  File [c:\Users\XXXXX\anaconda3\lib\site-packages\PyGeoStudio\__init__.py:1](file:///C:/Users/XXXXX/anaconda3/lib/site-packages/PyGeoStudio/__init__.py:1) in <module>
    from .PyGeoStudio import GeoStudioFile

  File [c:\Users\XXXXX\anaconda3\lib\site-packages\PyGeoStudio\PyGeoStudio.py:72](file:///C:/Users/XXXXX/anaconda3/lib/site-packages/PyGeoStudio/PyGeoStudio.py:72)
    match item:
          ^
SyntaxError: invalid syntax

**Comment by MoiseRousseau** [comment]
It seems to me you are using Python version 3.9 or below. You must have
Python 3.10 or above to run PyGeoStudio. Can you upgrade your Python
version ?
I can have a look tomorrow or later to make compatible with older Python
versions.

**Comment by RB-HGG** [comment]
All good now with Python update. Thanks!
