### ISSUE TITLE
No .xml file

### ISSUE THREAD

**Issue by RB-HGG** [MoiseRousseau/PyGeoStudio#12]
Hey there, 

When I try to load the Rapid drawdown.gsz file, I get the following KeyError:

"There is no item named 'C:\\\\Users\\\\XXXXX\\\\Downloads\\\\Rapid drawdown.xml' in the archive"

Is there a specific way I should be saving the GeoStuido files to allow pyGeoStudio to read them?

Cheers,
Ryan

**Comment by MoiseRousseau** [comment]
There is no special way to save GeoStudio file. However, you should not
rename the study, which is the common source for that error. Did you rename
it ? If yes, can you give the same name back ? Else, can you provide the
gsz file so I can have a look ?

**Comment by MoiseRousseau** [comment]
@RB-HGG : the new release is now able to open study with non-consistent main configuration file name (https://github.com/MoiseRousseau/PyGeoStudio/releases/tag/v0.4.3). Can you give it a try ?

**Comment by RB-HGG** [comment]
Hey Mosie, many thanks for this. It's all working now.

Cheers,
R


Ryan Burgess
, MSc., MIAH, MAusIMM
Senior Hydrogeologist
301 Blenheim Road, Upper Riccarton
​Christchurch 8041, New Zealand
T: +64 3 242 0221
M: +64 21 284 3999
www.hydrogeochem.com.au
CONFIDENTIALITY AND DISCLAIMER STATEMENTS
​
 This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone. Please contact the sender if you believe you have received this email in error. Emails and electronic files are not secure and cannot be guaranteed to be without error as they can be intercepted, amended, lost or destroyed, or contain viruses. Anyone who communicates with us by email is taken to accept these risks. Any advice provided in or attached to this email is subject to Hydro Geochem Group’s standard limitations.
