### ISSUE TITLE
Change analysis properties

### ISSUE THREAD

**Issue by panxuegang** [MoiseRousseau/PyGeoStudio#8]
In example file, why is it that every time I run the code change_saturated_perm.py successfully, I open the file Rapid drawdown.gsz with geostudio to see the material properties are still keep with the old edition.

**Comment by MoiseRousseau** [comment]
PyGeoStudio does not modify in place the original file, but it changes one copy in memory. You have to write it back on the hard drive with `geofile.writeGeoStudioFile(out_file)` where `out_file` is the name of the output. I push some modifications in the example folder. You can do `git pull` in PyGeoStudio root folder to update it.

**Comment by panxuegang** [comment]
Thank you for your answer, I work with a project that have requests to modify the reinforcement load. which function I can use to achive my request?

**Comment by MoiseRousseau** [comment]
This is no interface to the reinforcement load currently, but I can implement it pretty easily. What do you mean by modify the reinforcement load ? Which parameters in particular ?

**Comment by MoiseRousseau** [comment]
@panxuegang : I added the interface to reinforcement. You have an example in example/Reinforcements folder. Let me know your experience!
